on:
  push:
    branches:
      - main
      - master
      - dev
      - 'feature/**'
jobs:
  service_matrix:
    strategy:
      matrix:
        service: 
          - nfts-auth
          - nfts-polygon-adapter
          - nfts-stripe-adapter    
          - nfts-warehouse
          - nfts-notify
          - hubspot-proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          file: ${{ matrix.service }}/Dockerfile
          context: ${{ matrix.service }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/${{ matrix.service }}/cache

